### ISSUE TITLE
Rename Game1.cs

### ISSUE THREAD

**Issue by Ponsjuh** [mart90/Battleship#14]
It doesn't make sense. We need a logic name for this file

**Comment by ghost** [comment]
Dit is toch een nieuwe instantie van de game, NewGame zou toch prima zijn?

**Comment by FRizZL** [comment]
De naam Game1 slaat nergens op. dat zou samengevoegd moeten worden met MBRDgame

**Comment by ghost** [comment]
Maar er bestaat al een file met de naam MBRDGame.cs

Die naam kan je niet nog een keer gebruiken.
